### ISSUE TITLE
is there any reference on how to start with swiftUI?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [livekit/client-sdk-swift#10]

**Comment by hiroshihorie** [comment]
Hi @AlexanderKozhevin, I just started working on a SwiftUI example, updates to iOS SDK are on the way too.  SwiftUI example might be ready in about 2 weeks.

**Comment by doesnotexist** [comment]
@hiroshihorie gentle nudge, any update on this yet?

**Comment by hiroshihorie** [comment]
Hi @AlexanderKozhevin @doesnotexist 
You can try the new example repo (which uses swift UI)
https://github.com/livekit/client-example-swift

It will be updated to work with `main` of https://github.com/livekit/client-sdk-ios

**Comment by hiroshihorie** [comment]
I think the example code here https://github.com/livekit/client-example-swift demonstrates SwiftUI use case so I will close this for now.

Pre-compiled mac versions are available here https://github.com/livekit/client-example-swift/releases
