### ISSUE TITLE
Cocoapod support

### ISSUE THREAD

**Issue by Sudhanshudwivedi** [livekit/client-sdk-swift#101]
I want to add the iOS Livekit sdk to my cocoapod Library. As far as I know, we can't add the SPM directly in cocoapods. Is there any workaround for it? and also do you guys have any future plans to add the cocoapod support for the iOS SDK.

**Comment by baveku** [comment]
I found this library use URLWebSocket, it only supports >= iOS 12,
I think we can use another Websocket Library like [Starscream](https://github.com/daltoniam/Starscream) to support iOS 10 and work with all package managers(SPM, Cocoapods and Catharge)
