### ISSUE TITLE
How to set disable speakerphone?

### ISSUE THREAD

**Issue by std-s** [livekit/client-sdk-swift#105]
hi,
i can do it in Flutter:

```
  void _enableSpeakerphone(bool enabled) {
    LocalTrack? track;
    if (isVideo) {
      track = participant?.videoTracks.firstOrNull?.track;
    } else {
      track = participant?.audioTracks.firstOrNull?.track;
    }
    track?.mediaStreamTrack.enableSpeakerphone(enabled);
  }
```

but hot to do in iOS?

**Comment by hiroshihorie** [comment]
Hi, I think you can do that through `RTCAudioSession` but it might conflict with the SDK.
I'll try to get this working today.

**Comment by hiroshihorie** [comment]
Hi, with this PR https://github.com/livekit/client-sdk-swift/pull/107

you can call
`AudioManager.shared.preferSpeakerOutput = false`

**Comment by std-s** [comment]
> Hi, with this PR #107
> 
> you can call `AudioManager.shared.preferSpeakerOutput = false`

thx.
