### ISSUE TITLE
Adopting Picture in Picture

### ISSUE THREAD

**Issue by piercifani** [livekit/client-sdk-swift#129]
Starting iOS 15, we can adopt PiP for Video Calls, which seems very appropriate for this project. Do you know if it's possible? Doing a quick search for `import AV*` didn't bring up encouraging results...

## Links

- https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls

- https://stackoverflow.com/a/72470968/1152289

**Comment by hiroshihorie** [comment]
Hi @piercifani , I'm interested in PiP support and with this recent change it should be possible to implement it : https://github.com/livekit/client-sdk-swift/pull/120

You can get frames by adding a custom `VideoRenderer` and feed `CMSampleBuffer`s to `AVSampleBufferDisplayLayer`.

I will try to write an example when I have time.

**Comment by piercifani** [comment]
Great @hiroshihorie ! I'd very much appreciate that! But we still need a new version with those changes to be generated, right?

**Comment by hiroshihorie** [comment]
Hi, `VideoRenderer` protocol  and `VideoTrack.add(videoRenderer:)` is now in 1.0.5
I will close this for now.

I will let you know if I manage to implement a demo using PiP.

**Comment by afgarcia86** [comment]
Would love to see an example of this.

**Comment by elesahich** [comment]
Hi, are there any updates for an example?
