### ISSUE TITLE
Random crash on StateSync.readCopy()

### ISSUE THREAD

**Issue by v57** [livekit/client-sdk-swift#139]
Looks like a deadlock, but layout subviews called from main thread and `performLayout()` also checks for main thread right before executing this function

![Screenshot 2022-09-14 at 11 07 16](https://user-images.githubusercontent.com/2669441/190097945-8bdd2332-e4e9-4f4d-96e8-c80f35718777.png)

**Comment by v57** [comment]
I'm using latest 1.0.5 version. Tested on iPad OS 16 Beta and macOS 12.5 (designed for iPad). Xcode 14, swift 5.7

**Comment by hiroshihorie** [comment]
I suppose VideoView is crashing, can I see how you are using it ?

**Comment by v57** [comment]
I have different task so i'm closing this issue. It was crashing after i change or remove video tracks multiple times
