### ISSUE TITLE
-[RTCConfiguration setSdpSemantics:]: unrecognized selector sent to instance 0x283

### ISSUE THREAD

**Issue by leeqiangzi** [livekit/client-sdk-swift#153]
Error message：
2022-10-26 16:40:09.750388+0800 JL[18221:962080] -[RTCConfiguration setSdpSemantics:]: unrecognized selector sent to instance 0x283560600

Initialized according to the official website prompt
@objc class KSLiveKitManager: NSObject {
    
    lazy var room = Room(delegate: self)

    /// 链接
    @objc
    func connect(url: String, token: String) {
        room.connect(url, token);
    }
    
    /// 离开房间，断开链接
    @objc
    func disconnect() {
        room.disconnect();
    }
}

extension KSLiveKitManager: RoomDelegate {

    func room(_ room: Room, localParticipant: LocalParticipant, didPublish publication: LocalTrackPublication) {
    }
    
    func room(_ room: Room, participant: RemoteParticipant, didSubscribe publication: RemoteTrackPublication, track: Track) {
    }
}

**Comment by hiroshihorie** [comment]
Closing duplicate issue
