### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by leeqiangzi** [livekit/client-sdk-swift#154]
2022-10-26 17:24:51.007108+0800 JL[18454:973350] -[RTCConfiguration setSdpSemantics:]: unrecognized selector sent to instance 0x283c7b300

[Crash-image](https://upload-images.jianshu.io/upload_images/2356976-a1be6691dc06e172.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
https://upload-images.jianshu.io/upload_images/2356976-a1be6691dc06e172.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by davidzhao** [comment]
I'd like to remind you again to please stop filing duplicate issues. Please provide additional information to the same issue that you've opened in #153
