### ISSUE TITLE
`sdpSemantics` property not found crash

### ISSUE THREAD

**Issue by leeqiangzi** [livekit/client-sdk-swift#155]
-[RTCConfiguration setSdpSemantics:]: unrecognized selector sent to instance 0x281ffc960

Specific location：
````
    public static func liveKitDefault() -> RTCConfiguration {

        let result = DispatchQueue.webRTC.sync { RTCConfiguration() }
        result.sdpSemantics = .unifiedPlan
        result.continualGatheringPolicy = .gatherContinually
        result.candidateNetworkPolicy = .all
        result.tcpCandidatePolicy = .enabled
        result.iceTransportPolicy = .all

        result.iceServers = [ DispatchQueue.webRTC.sync { RTCIceServer(urlStrings: defaultIceServers) } ]

        return result
    }
`````

‘DispatchQueue.webRTC.sync { RTCConfiguration() }'，
No crash caused by sdpSemantics exists in the returned object；Is there any solution？，Call de exactly according to the document。

Thank you.

**Comment by davidzhao** [comment]
hi, which version are you running on? can you provide any repro steps?

**Comment by leeqiangzi** [comment]
The latest pod 1.0.6 updated yesterday

**Comment by leeqiangzi** [comment]
`
@objc class KSLiveKitManager: NSObject {
    override init() {
        super.init();
    }
    
    lazy var room = Room(delegate: self)
    
    /// 链接
    @objc
    func connect(url: String, token: String) {
        room.connect(url, token);
    }
    
    /// 离开房间，断开链接
    @objc
    func disconnect() {
        room.disconnect();
    }
}

extension KSLiveKitManager: RoomDelegate {

    func room(_ room: Room, localParticipant: LocalParticipant, didPublish publication: LocalTrackPublication) {
        
    }
    
    func room(_ room: Room, participant: RemoteParticipant, didSubscribe publication: RemoteTrackPublication, track: Track) {

    }
}
`

**Comment by leeqiangzi** [comment]
@objc class KSLiveKitManager: NSObject {
    override init() {
        super.init();
    }
    
    lazy var room = Room(delegate: self)
    
    /// 链接
    @objc
    func connect(url: String, token: String) {
        room.connect(url, token);
    }
    
    /// 离开房间，断开链接
    @objc
    func disconnect() {
        room.disconnect();
    }
}

extension KSLiveKitManager: RoomDelegate {

    func room(_ room: Room, localParticipant: LocalParticipant, didPublish publication: LocalTrackPublication) {
        
    }
    
    func room(_ room: Room, participant: RemoteParticipant, didSubscribe publication: RemoteTrackPublication, track: Track) {

    }
}

**Comment by leeqiangzi** [comment]
We are very anxious. We hope you can repair it as soon as possible. Thank you

**Comment by leeqiangzi** [comment]
pod 'LiveKitClient', '1.0.6'

**Comment by leeqiangzi** [comment]
Can you find the problem from the information I provided？

**Comment by hiroshihorie** [comment]
I'm investigating this, it might be Cocoapods related.
Can you give me the steps to replicate this ?

**Comment by leeqiangzi** [comment]
1. Use cocopods to manage, pod 'LiveKitClient', '1.0.6'
2. This problem will occur if you link directly with url and token
3. The specific tool code is as follows



@objc class KSLiveKitManager: NSObject {
    override init() {
        super.init();
    }
    
    lazy var room = Room(delegate: self)
    
    /// 链接
    @objc
    func connect(url: String, token: String) {
        room.connect(url, token);
    }
    
    /// 离开房间，断开链接
    @objc
    func disconnect() {
        room.disconnect();
    }
}

**Comment by leeqiangzi** [comment]
The main problem is why there is no sdpSemantics in the RTCConfiguration returned by the webRTC, leading to a crash when assigning values. We did nothing outside, which means we called the link

**Comment by leeqiangzi** [comment]
Hello, do you have any progress？

**Comment by leeqiangzi** [comment]
![2222222](https://user-images.githubusercontent.com/15033611/198230690-efe9dcf2-cd67-49a0-85eb-24e1b066f6c4.jpeg)
![21212121](https://user-images.githubusercontent.com/15033611/198230716-85806717-3f0f-4975-83a8-691f06a99ab3.jpeg)

**Comment by hiroshihorie** [comment]
Are you using the ObjC version ?

**Comment by leeqiangzi** [comment]
ObjC or swift have problems

**Comment by leeqiangzi** [comment]
What I'm using now is to create a swfit class that calls livekit, and then calls swift with ObjC

**Comment by leeqiangzi** [comment]
I really don't understand what's going on. I've been looking forward to your reply

**Comment by leeqiangzi** [comment]
My code is ObjC, but you use Cocopods integration 1.0.6 to integrate, and use the bridge file to call swift

**Comment by hiroshihorie** [comment]
I can't reproduce this at the moment.

**Comment by leeqiangzi** [comment]
I will provide you with a Github demo later, about

**Comment by hiroshihorie** [comment]
Can I see your Podfile.lock file ?

**Comment by leeqiangzi** [comment]
- LiveKitClient (1.0.6):
    - Logging
    - PromisesSwift
    - SwiftProtobuf
    - WebRTC-SDK (~> 104.5112.05)

**Comment by hiroshihorie** [comment]
Looks correct.... can you prepare a small demo ? thanks.

**Comment by leeqiangzi** [comment]
Hello, first of all, thank you very much for your reply. The reason for the problem has been found. It is because one of the other static libraries (. a) in our project references a lower version of webrtc. The 'RTCConfiguration' class in this version does not define the 'sdpSemantics' attribute
I also want to ask you whether we can still use LiveKit if a low version of WebRtc exists in the project and cannot be modified. Do you have a solution here

**Comment by leeqiangzi** [comment]
LiveKit is very important to us. Another library that references low version WebRtc is also important to us, but they can't modify it. We use LiveKit only for voice calls, and 'url' and 'token' are connected. Is there a better way to use LiveKit? For example, low version WebRtc is used in low version livekits, but only version 1.0.6 is seen in the current pod management

**Comment by leeqiangzi** [comment]
The lower version is probably the 2016 version of webrtc

**Comment by hiroshihorie** [comment]
Oh ok that makes a lot of sense it would crash.
You can fork this repo and reference your preferred WebRTC version and comment out the `sdpSemantics` property.

**Comment by leeqiangzi** [comment]
Hello, I'd like to ask, what is the minimum version of livekit supported on pod? At present, there is only one 1.0.6

**Comment by hiroshihorie** [comment]
@leeqiangzi I think you can use previous versions .
