### ISSUE TITLE
Write a small PIP VideoView example

### ISSUE THREAD

**Issue by hiroshihorie** [livekit/client-sdk-swift#172]
There has been several requests for this.

**Comment by DnTest34324532** [comment]
+1

**Comment by elesahich** [comment]
Any Updates?

**Comment by elesahich** [comment]
@hiroshihorie has a draft pr for experimental PiP support. 👀 We can see it in #222

**Comment by hiroshihorie** [comment]
@elesahich Yup working on it !

**Comment by hiroshihorie** [comment]
Closing this, I have a minimal pip example here:
https://github.com/livekit-examples/swift-example-collection/tree/main/minimal-pip
