### ISSUE TITLE
Screen sharing stop when app in background

### ISSUE THREAD

**Issue by vuongxuantuyen** [livekit/client-sdk-swift#182]
I take screen sharing with this instruction: https://github.com/livekit/client-sdk-swift/wiki/iOS-Screen-Sharing. Every thing work fine except the screen sharing will stop when enter background. The same issue on the example application too. Do you have any idea?

**Comment by hiroshihorie** [comment]
Can you try publishing an audio track before going into background ?

**Comment by std-s** [comment]
@vuongxuantuyen  hi，any solution？

**Comment by elesahich** [comment]
I've found a few other apps that I can reference, but implementing PiP seems to be the only way to go. Are there any solutions?

**Comment by elesahich** [comment]
For me a day ago : PiP was not an answer :)......

**Comment by hiroshihorie** [comment]
Hello can you try the solution here :
https://github.com/livekit/client-sdk-swift/issues/219
Set RoomOptions.suspendLocalVideoTracksInBackground to false.

**Comment by vuongxuantuyen** [comment]
@hiroshihorie It work, thank you.
