### ISSUE TITLE
How to use iOS screen sharing in native projects?

### ISSUE THREAD

**Issue by std-s** [livekit/client-sdk-swift#187]
Hi,
How to use iOS screen sharing in native projects? Sorry, no relevant examples were found.

**Comment by std-s** [comment]
> @std-s You can see the example here: https://github.com/livekit/client-sdk-swift/wiki/iOS-Screen-Sharing

@vuongxuantuyen Hi,

But it will report an error "'RTCCameraVideoCapturer' is unavailable in application extensions for iOS: Camera not available in app extensions."

**Comment by std-s** [comment]
@vuongxuantuyen  After turning on screen sharing, why can't I capture the desktop image?

**Comment by davidzhao** [comment]
Did you add the broadcast extension?

**Comment by std-s** [comment]
> Did you add the broadcast extension?
@davidzhao Hi,

It is turned on, but after retreating to the background. Other members cannot receive the stream.

**Comment by davidzhao** [comment]
I believe that's a limitation of iOS and backgrounding. In order for background publishing to work, you need to be publishing an audio track.

**Comment by std-s** [comment]
@davidzhao 
Hi, 
When it is about to switch to the background, the following code is executed, but it will still be interrupted.

`let audioTrack = LocalAudioTrack.createTrack()`
 `room.localParticipant?.publishAudioTrack(track: audioTrack)`
