### ISSUE TITLE
How to record audio in the room (Streamer + Co-Streamer)? 

### ISSUE THREAD

**Issue by isandeepj** [livekit/client-sdk-swift#188]
Not able to find method or documation for related to this?

**Comment by hiroshihorie** [comment]
You might be looking for https://github.com/livekit/egress which can be done on the server side .

**Comment by sandeep-yudiz** [comment]
I need to capture audio for specific duration on client side to to records happy moments of the livestreams. This will not work for me!

**Comment by hiroshihorie** [comment]
Client side recording of video / audio is not supported yet.

**Comment by sandeep-yudiz** [comment]
Can we provide the support?

**Comment by hiroshihorie** [comment]
Do you have ideas on how to implement this ?

**Comment by sandeep-yudiz** [comment]
Please take this reference https://github.com/mstyura/RTCAudioDevice/tree/main

**Comment by isandeepj** [comment]
@hiroshihorie any update on this?

**Comment by hiroshihorie** [comment]
You now can hook into the whole mixed audio out with `AudioManager.renderPreProcessingDelegateAdapter`.
You will need to write your own `AudioCustomProcessingDelegateAdapter` and convert samples to `CMSampleBuffer`s etc and write it to a file. I aim to make this more developer friendly eventually.

`RemoteAudioTrack` as `add(audioRenderer:)` also to capture audio from individual tracks.

**Comment by denis-obukhov** [comment]
Is it possible to add AudioRenderer to a local audio track?

**Comment by hiroshihorie** [comment]
No this method won't work for local tracks. But you can use AudioManager.capturePostProcessingDelegate and intercept frames.
