### ISSUE TITLE
Sending video and audio over our custom camera class.

### ISSUE THREAD

**Issue by sajjadsarkoobi** [livekit/client-sdk-swift#190]
Is there a way to send stream data over [captureOutput(_:didOutput:from:)](https://developer.apple.com/documentation/avfoundation/avcapturevideodataoutputsamplebufferdelegate/1385775-captureoutput) ? 

So in that case we can do our own manipulation on video layer or do some ML on local camera capturing while we are streaming the raw video with LiveKit.

Thanks

**Comment by hiroshihorie** [comment]
You can create a `BufferCapturer` track and feed `CVPixelBuffer` or `CMSampleBuffer`. But you will need to setup the camera capturing -> frame processing part your self.

**Comment by hiroshihorie** [comment]
Hey I will close this for now.

**Comment by Yabby1997** [comment]
@hiroshihorie Hey, I got a question related to this. It seems `BufferCapturer` is an implementation of `VideoCapturer` and thus, those two methods you commented, `capture(_:timeStampNs:rotation:)` and `capturer(_:)` seems only for "Video". Is there a way to feed custom audio buffer?
