### ISSUE TITLE
room(_:, participant:, didPublish:) is never called (remoteVideoView)

### ISSUE THREAD

**Issue by Gargo** [livekit/client-sdk-swift#191]
**Describe the bug**
Can't display remote track view and don't know how to debug it properly. Used code similar to the one from readme. The main difference is local and remote view containers are placed into UIStackView.
Tried to look at your examples but don't see any significant difference.
How to detect if it is ok with remote video?
The issue is similar to this one:
https://github.com/livekit/client-sdk-swift/issues/61

**SDK Version**
1.0.9

**iOS/macOS Version**
iOS 14.6

**Steps to Reproduce**
-

**Expected behavior**
`room(_:, participant:, didPublish:)` is called, remoteVideoView is set, remote video is displayed

**Screenshots**
nothing to display

**Logs**
-

**Comment by hiroshihorie** [comment]
`didPublish` is for local user publishing.
use `didSubscribe` for remote tracks.

**Comment by hiroshihorie** [comment]
Hello, I just checked and it looks like it's working. This delegate method will not be called for tracks that are already published.

You can see these methods called in the example https://github.com/livekit/client-example-swift/commit/c79674f736858a704dfcc0fb1096abe77353fda3#diff-e4c381aef3c3ce054136c2cdf6187668e82d4e7db51b6e720b34d676a4177dc0

**Comment by Gargo** [comment]
Don't know what is the reason of this behaviour. Tried to create a wrapper over LiveKit - it doesn't work, inserted directly into view controller like in your example - it work.
