### ISSUE TITLE
Thread deadlock when simultaneously publishing 3+ tracks

### ISSUE THREAD

**Issue by hiroshihorie** [livekit/client-sdk-swift#209]
**Describe the bug**
Thread deadlock when simultaneously publishing 3+ tracks.
Does not happen when published in sequential order.

**SDK Version**
1.0.9

**iOS/macOS Version**
Both

**Steps to Reproduce**
Publish simultaneously by resolving publish completers with `all(...)`.

**Comment by jam0128** [comment]
We have a same issue 🫠

**Comment by hiroshihorie** [comment]
Hi @jam0128 , sorry to hear this. I'll try to find a workaround. 
What if you publish in sequential order instead of simultaneously, does it help ?

**Comment by shalom-aviv** [comment]
@hiroshihorie 
What do you mean "sequential order instead of simultaneously"?
Thank you

**Comment by hiroshihorie** [comment]
This should be fixed in v2, closing this.
