### ISSUE TITLE
Go Offline - Update Participant Status

### ISSUE THREAD

**Issue by dcflow** [livekit/client-sdk-swift#211]
Hi,

I have participant A and B connect to a room. Participant B goes offline. How does participant A know that participant B has lost connection?

I have tried the `ParticipantDelegate didUpdateConnectionQuality` and that changes to `poor` for participant B. I have tried the `TrackDelegate didUpdateStats` and that makes the `bps 0`, but it's CPU intensive. And `participantDidLeave` takes a long time to get called. Is there another delegate method that can be used?

I don't know what's the timeout to cut out participant B, but I think there should be another method in `ParticipantDelegate` that gets called when participant is no more sending data.

What do you guys think?

**Comment by hiroshihorie** [comment]
Do you want to know why the participant disconnected ?
Or do you want to know the user stopped publishing video ?

**Comment by enyars** [comment]
Yes, so I want to know that it has stopped publishing the track, the reason why is not important.

The connection on participant B is lost completely so I suppose it doesn't go through the `didUnpublish` or `didUnsubscribe` delegates.

**Comment by dcflow** [comment]
Yes, so I want to know that it has stopped publishing the track, the reason why is not important.

The connection on participant B is lost completely so I suppose it doesn't go through the didUnpublish or didUnsubscribe delegates.

**Comment by hiroshihorie** [comment]
I think the short time lag ins unavoidable because the user might have a bad network and automatic re-connection might be in progress. I think watching those delegates are correct.

**Comment by dcflow** [comment]
Ok, I understand. Is there a way to modify the failure timeout? Right now is 20+ seconds, and that for some scenarios is a bit too much to wait for retries.

**Comment by davidzhao** [comment]
unfortunately there isn't. these are values built into webrtc timeouts. if participant B calls `Room.disconnect`, we'll be able to capture that event immediately without delay. But if they are just going offline, that is a moot point anyways..

**Comment by dcflow** [comment]
Ok thank you both for your answers, really appreciate it!
