### ISSUE TITLE
Release 1.0.13 to CocoaPods

### ISSUE THREAD

**Issue by silviudeac** [livekit/client-sdk-swift#214]
The latest version of the library published using CocoaPods is 1.0.8 which has significant API differences to the latest official version: 1.0.13

LiveKit is used inside one of our frameworks so we cannot use the CocoaPods tag mechanism, nor can we use Swift Package Manager due to other external restrictions.

Please publish the latest version.

**Comment by hiroshihorie** [comment]
1.0.13 Published !
