### ISSUE TITLE
Failed to verify module interface of 'Promises.'

### ISSUE THREAD

**Issue by indaos** [livekit/client-sdk-swift#215]
**Describe the bug**
 if I add a LiveKit client dependency to a project that has "BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
 the build process will fail due to an error: failed to verify module interface of 'Promises.'

**iOS/macOS Version**
Xcode 14.3

**Steps to Reproduce**
if we create an empty app, add  LiveKit framework (SwiftPM) and add BUILD_LIBRARY_FOR_DISTRIBUTION=YES,
 it will cause a problem 
**Logs**
/Build/Intermediates.noindex/Promises.build/Release-iphoneos/Promises.build/Objects-normal/arm64/Promises.private.swiftinterface:5:8: error: no such module 'FBLPromises'
import FBLPromises
       ^
/Build/Intermediates.noindex/Promises.build/Release-iphoneos/Promises.build/Objects-normal/arm64/Promises.private.swiftinterface:1:1: error: failed to verify module interface of 'Promises' due to the errors above; the textual interface may be broken by project issues or a compiler bug
// swift-interface-format-version: 1.0
^

**Comment by hiroshihorie** [comment]
Hi, I've started working on removing dependencies on Promises lib.

**Comment by hiroshihorie** [comment]
v2 doesn't use Promises any more, can you migrate ?
Closing this for now.
