### ISSUE TITLE
Does livekit swift sdk support SwiftUI?

### ISSUE THREAD

**Issue by clarkshu1016** [livekit/client-sdk-swift#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shalom-aviv** [comment]
Did you check link in Readme?
[iOS/macOS Swift UI Example App](https://github.com/livekit/client-example-swift)

**Comment by hiroshihorie** [comment]
Yes we support SwiftUI, main objects such as Room, Participant etc are `ObservableObjects` .
Also I'm working on Swift UI components to make development more simpler.
