### ISSUE TITLE
use Broadcast Upload Extension, bug screen sharing doesn't work in the background

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-swift#219]
I configured screen sharing according to this wiki: https://github.com/livekit/client-sdk-swift/wiki/iOS-Screen-Sharing

But there is a problem, after entering the background, the screen sharing stops.

`background mode` has been set. `Broadcast Upload Extension` has been imported.

but when the App enters the background, it will stop screen sharing, and the system prompts: Your App has stopped screen sharing for some reason. As shown in the picture:

![](https://s2.loli.net/2023/06/21/zIne1X4NBlk69vF.jpg)

I checked the memory usage of this Extension, it is not very high, generally between 8-20M.

By running `Broadcast Upload Extension`, some logs are recorded when the extension stops:

2023-06-21 22:06:22.890540+0800 BroadcastExtension[6966:290838] [Broadcast] server socket closed
2023-06-21 22:06:22.890778+0800 BroadcastExtension[6966:290838] [Broadcast] client connection did close nil
Program ended with exit code: 9

**Comment by wzJun1** [comment]
Screen sharing in my App is normal, but after entering the background for about 1-2 seconds, it will be disconnected and the above pop-up window will be prompted.

Before entering the background, the audio streaming has been going on, and the call is normal.

**Comment by wzJun1** [comment]
I print error log in `setupConnection` method in `LKSampleHandler.swift` file, `print(error)`, it is nil

I don't know what caused it, guess it's like the `Extension` process was killed

**Comment by wzJun1** [comment]
I found a sample App with the same problem:

https://github.com/livekit-examples/swift-example/

**Comment by elesahich** [comment]
👀

**Comment by wzJun1** [comment]
> What version are you using? Same here with 1.0.13. 👀

It should be the latest version, because I am directly clone git

**Comment by wzJun1** [comment]
The problem is that I used the case and the same problem occurred. Case URL:

https://github.com/livekit-examples/swift-example/

**Comment by elesahich** [comment]
In my case, I think this is an iOS specific issue, as Android and Web SDK work fine even if they go into the background or something.

**Comment by wzJun1** [comment]
> In my case, I think this is an iOS specific issue, as Android and Web SDK work fine even if they go into the background or something.

So is this problem insoluble? I want to seek a solution. Because I noticed that other apps do not have this issue, their screen sharing is normal, such as Zoom

**Comment by elesahich** [comment]
No, I don't think you're asking me because I don't know either. I'm a library user like you.

**Comment by elesahich** [comment]
I also want a solution to this issue. :)

**Comment by wzJun1** [comment]
> I also want a solution to this issue. :)

Okay, then wait for the author's reply

**Comment by elesahich** [comment]
Hey @wzJun1, I found [Room.swift#374](https://github.com/livekit/client-sdk-swift/blob/main/Sources/LiveKit/Core/Room.swift#L374) causes all video tracks to suspend when going to background. So if you want to continue screensharing in the background, you have to change this line to not suspend [like this](https://github.com/elesahich/client-sdk-swift/commit/5d1085d13ad086bbdfd71ffbcb5d68d7fd5f7a04) or so on.

**Comment by elesahich** [comment]
It works, but please use it cautiously, as this may not be the maintainer's intention.

**Comment by elesahich** [comment]
AH There is a property named `suspendLocalVideoTracksInBackground` in RoomOption. It will be not triggered mark this flag to `false`. this is not bug.

**Comment by wzJun1** [comment]
@elesahich Thanks for your help, I'll try to debug it.

**Comment by wzJun1** [comment]
@elesahich 

Thank you very much, problem solved.

This problem bothered me for a day and caused me to be in a bad mood, now everything is calm, thank you again

**Comment by hiroshihorie** [comment]
Thanks guys for looking into this, I think `suspendLocalVideoTracksInBackground` shouldn't affect screen share tracks. 
I'll patch this.
