### ISSUE TITLE
How to audio mute/unmute or volume increase/decrease remote participants' audio, so only I will not hear it.

### ISSUE THREAD

**Issue by isandeepj** [livekit/client-sdk-swift#220]
If the viewer joins the stream, then how to do we can **audio** mute/unmute or **volume increase or decrease** the stream for viewers?

Can you please provide the code snippet or methods? I can't able to find its documentation page.

**Comment by hiroshihorie** [comment]
Do you mean you want to mute remote participant's audio ?

**Comment by sandeep-yudiz** [comment]
Yes

**Comment by hiroshihorie** [comment]
Sorry for the late reply but you can unsubscribe that track. or you can try the `RemoteAudioTrack.volume` property.

**Comment by hiroshihorie** [comment]
Please re-open if you can't make it work.
