### ISSUE TITLE
when I turn on screen sharing and turn it off, turn it on again, it doesn't work

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-swift#223]
when I turn on screen sharing and turn it off, turn it on again, it doesn't work.

case has the same problem：https://github.com/livekit/client-example-collection-swift

Now my solution is to execute `unpublish` when it is closed:

```
if(source == Track.Source.screenShareVideo){
    unpublish(publication: publication, notify: true)
} 
```

hope the author can provide a better solution, thanks!

**Comment by wzJun1** [comment]
There is another problem. When `RPSystemBroadcastPickerView` is called, it displays the selection screen mirroring. If you do not confirm to start the live broadcast at this time, but return to the original page, there is no event to listen to. At this time, the `setScreenShare` method has some problems, because it It has been confirmed that the screen sharing has been done internally, but the screen sharing did not actually start (because I did not click to start the live broadcast, but returned to the original page).

**Comment by wzJun1** [comment]
It will result in: room.localParticipant.isScreenShareEnabled is true

Or it will cause other problems that have not been discovered

**Comment by std-s** [comment]
I also encountered the same problem.

**Comment by saeidbasirnia** [comment]
+1

**Comment by monkeyttttt** [comment]
unpublish,but RPSystemBroadcastPickerView Cann't be closed.Is there any way to solve？

**Comment by wzJun1** [comment]
I call `unpublish` to cancel the track, and `Broadcast` will stop after about 5 seconds.

LocalParticipant.swift:

`public func set`

```
if let publication = getTrackPublication(source: source) as? LocalTrackPublication {
            if enabled {
                return publication.unmute().then(on: queue) { publication }
            } else {
                //This is the new code
                return publication.mute().then(on: queue) {
                    if(source == .screenShareVideo){
                        self.unpublish(publication: publication).then { _ in
                            
                        }
                    }
                    return publication
                }
            }
        }
```



> unpublish,but RPSystemBroadcastPickerView Cann't be closed.Is there any way to solve？

**Comment by wzJun1** [comment]
Currently, I am at 540 resolution and screen sharing is fully functioning. I think I can close this issue.

**Comment by monkeyttttt** [comment]
I haven't solved it yet。is there any Wrong?

when turn off shareScreen, the Broadcast is still exist
![WechatIMG42](https://github.com/livekit/client-sdk-swift/assets/4243863/41f81761-788a-4ff8-9fd7-919f4627ffc0)

IBAction func shareOrNot(_ sender: UIButton) {
        sender.isSelected = !sender.isSelected
        room.localParticipant?.setScreenShare(enabled: sender.isSelected)
        if(!sender.isSelected){
            let publications = localParticipant?.localVideoTracks.filter({$0.source == .screenShareVideo})
            if let localTrackPublication = publications?.first{
                localTrackPublication.mute().then{[weak self] in
                    self?.localParticipant?.unpublish(publication: localTrackPublication).then{
                    
                    }
                }
            }
        }
    }

**Comment by wzJun1** [comment]
Which version? I'm using `1.0.14` and this doesn't happen.

You might be able to check if `notifyDidClose` in `BroadcastUploadSocketConnection` is called?

**Comment by monkeyttttt** [comment]
> notifyDidClose

the version is  1.1.6

notifyDidClose in  BroadcastUploadSocketConnection don't be called

**Comment by wzJun1** [comment]
I think 1.1.6 is not a stable version yet, it is recommended to use 1.0.14

**Comment by wzJun1** [comment]
The solution to this issue(#223) is `unpublish`, now I will close it.

**Comment by monkeyttttt** [comment]
> I think 1.1.6 is not a stable version yet, it is recommended to use 1.0.14

replace 1.0.14 version sdk,the problem is still exist.  the ios version is  17.1.1

**Comment by wzJun1** [comment]
Sorry I don't have this version of iphone

You can @ author @hiroshihorie 

> > I think 1.1.6 is not a stable version yet, it is recommended to use 1.0.14
> 
> replace 1.0.14 version sdk,the problem is still exist. the ios version is 17.1.1

**Comment by mokuzuu** [comment]
> There is another problem. When `RPSystemBroadcastPickerView` is called, it displays the selection screen mirroring. If you do not confirm to start the live broadcast at this time, but return to the original page, there is no event to listen to. At this time, the `setScreenShare` method has some problems, because it It has been confirmed that the screen sharing has been done internally, but the screen sharing did not actually start (because I did not click to start the live broadcast, but returned to the original page).

Hi @wzJun1 Do you know the status of this one? I've faced the same issue
