### ISSUE TITLE
Fix - Connection drop on audio mix

### ISSUE THREAD

**Issue by dcflow** [livekit/client-sdk-swift#227]
https://github.com/livekit/client-sdk-swift/blob/fcc124dcce9052f53ae878d7dbd8e7b256b2e63e/Sources/LiveKit/Track/AudioManager.swift#L143

Can we add `mixWithOthers` here so the connection doesn't drop when another audio starts playing `[.mixWithOthers, .defaultToSpeaker]`?

**Comment by hiroshihorie** [comment]
Hello, is this causing issues ? Thanks for discovering this.

**Comment by hiroshihorie** [comment]
Fixed in the PR, thanks !
