### ISSUE TITLE
Xcode 15 showing error 'No such module 'Promises'

### ISSUE THREAD

**Issue by zubingala** [livekit/client-sdk-swift#255]
I upgraded to Xcode 15,  I'm getting this error No such module 'Promises' inside BroadcastScreenCapturer.swift file.

**iOS/macOS Version**
Xcode 15.0

<img width="1440" alt="Screenshot 2023-10-03 at 2 09 55 PM" src="https://github.com/livekit/client-sdk-swift/assets/15726234/4acaef35-0006-4afc-aebd-c5943172ad44">

**Comment by hiroshihorie** [comment]
Hey, I stripped out Promises lib for the upcoming v2 release. Will close this one.
