### ISSUE TITLE
It looks like the three connection state change delegates are not being call

### ISSUE THREAD

**Issue by trzeciak** [livekit/client-sdk-swift#258]
**Describe the bug**
It looks like the three connection state change delegates are not being call.

This delegate is called:
```swift
@objc
public protocol RoomDelegateObjC: AnyObject {

    @objc(room:didUpdateConnectionState:oldConnectionState:) optional
    func room(_ room: Room, didUpdate connectionState: ConnectionStateObjC, oldValue oldConnectionState: ConnectionStateObjC)
```

but those three delegates are not called at all:
```swift
    /// Successfully connected to the room.
    @objc(room:didConnectIsReconnect:) optional
    func room(_ room: Room, didConnect isReconnect: Bool)

    /// Could not connect to the room.
    @objc(room:didFailToConnectWithError:) optional
    func room(_ room: Room, didFailToConnect error: Error)

    /// Client disconnected from the room unexpectedly.
    @objc(room:didDisconnectWithError:) optional
    func room(_ room: Room, didDisconnect error: Error?)
```

I know that the first delegate covers the functionality of the others, but I'm just starting with LiveKit and I wasted a lot of time on it.

**SDK Version**
Latest version: 1.1.2.

**iOS/macOS Version**
iOS 17 (simulator)

**Steps to Reproduce**
Implement these delegates and check if they are called after the connection.

**Expected behavior**
Call appropriate delegates or remove unused interfaces.

**Comment by hiroshihorie** [comment]
Not sure how this slipped out, thanks for reporting.
Yes the `didUpdate:connectionState` is recommended since it provides more info (Disconnect reason).
I think I was going to deprecate it or replace it, but for now it should be called.
Patched: https://github.com/livekit/client-sdk-swift/commit/cc56faa6cc3a5a651425f0bae3142c167ccf79fe
