### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by amrendradevios** [livekit/client-sdk-swift#264]
We want to create a voice call application for the VisionOS simulator; however, it appears that LiveKit lacks support for this platform. During the process of building for the VisionOS simulator, we encountered an issue where no library for this platform was found within the 'artifacts/specs/WebRTC/WebRTC.xcframework' directory. We managed the integration of LiveKit through SPM "client-sdk-swift".

Has anyone successfully compiled LiveKit for the VisionOS simulator?

Thanks in advance

**Comment by hiroshihorie** [comment]
As of now we don't support _visionOS_ but we **have plans to support this** 😎

**Comment by maxbbb** [comment]
Hi, any updates on this? Don't know what it would entail but happy to help if I can.

**Comment by PaulAddy** [comment]
Support visionOS please

**Comment by matt953** [comment]
We have use-cases that also require support for VisionOS as well. Primarily for spatial experiences and consuming streams from iOS/Web.

**Comment by davidzhao** [comment]
we are working on this folks! will have some news in ~ a month
