### ISSUE TITLE
Sometimes user can't connect to Room with error TransportError.timedOut  primary transport didn't connect

### ISSUE THREAD

**Issue by NoliNik** [livekit/client-sdk-swift#274]
**Describe the bug**
Sometimes ours 2  users (from around 100 active) can't connect to Room with error
TransportError.timedOut  primary transport didn't connect
Bug reproduce on Wifi and Cellular. 
The connection quality is good or even excellent 
When user get such error with timeout and retry to call in 95 % connection establish in 1-3 sec

**SDK Version**
IOS SDK 1.1.2
Server 1.5.1

**iOS/macOS Version**
iOS  16.6.1

**Steps to Reproduce**
just calling,  incoming or outcoming calls

**Expected behavior**
user  connect to room every time

**From server side** we looked at open issues and 
 We try change location for livekit server 
try change some setting 
 corrently:
    use_external_ip: false
turn: enabled: true
Also we try to change location for livekit server 

**Important Note**
We assumed that the problem is in the UDP connection.
For example, when switching between UDP and TCP.
To continue research, we force enabled TCP on the server and the problem changed.
The timeout error no longer appears. Now there are no logs until the user hangs up in 15 or more seconds (timeout should trigger at 10 seconds) 

**log**

```
[2023-11-15T12:30:57_343+0300:]
"[CALLS:LKROOM]: Start join room"

[12:30:57_356+0300:]
"[CALLS:LKROOMDELEGATE]: room.[]> didUpdate: connecting, oldValue: disconnected(reason: nil"

[12:30:57_356+0300:]
"[CALLS:LKCONNECTION]: VideoConf activity: connecting(1), сallId id of call"

[12:30:57_356+0300:]
"[CALLS:CALL]: Connecting - call: (id: id of call 

[12:30:57_360+0300:]
"[CALLS:LKCONNECTION]: VideoConf participant status: inactive(0), сallId id of call"

[12:30:57_621+0300:]
"[CALLS:LKROOMDELEGATE] - room(_:participant:didUpdate:)]: room.name[room name here]> participant: current user., didUpdate: {"userDetails”:{current user details here}"}}"

[12:30:57_621+0300:]
"[CALLS:LKROOMDELEGATE]]: room.name[room name here]> participant:  current user., didUpdate: some_permissions"

[12:31:02_978+0300]
"[CALLS:LKROOMDELEGATE]: room.name[room name here]> participant: opponent, didUpdate: {"userDetails":{“opponent details here"}}"

[12:31:07_682+0300]
"[CALLS:LKROOMDELEGATE]: room.name[room name here]> didUpdate: disconnected(reason: networkError: Не удалось завершить операцию. (LiveKit.TransportError, ошибка 0), oldValue: connecting"
```

Need some ideas to continue investigate issue
Thanks guys in advance

**Comment by davidzhao** [comment]
`use_external_ip: false` is not supported for a production setup. this means you are relying on STUN to function on both server and client.  Please ensure that [connection test](https://livekit.io/connection-test) passes before opening issues.
