### ISSUE TITLE
subscription and unsubscription track in Objective-C

### ISSUE THREAD

**Issue by cl252738669** [livekit/client-sdk-swift#277]
In Swift, i can achieve subscription and unsubscription like this:
/// Subscribe or unsubscribe from this track.
@discardableResult
public func set(subscribed newValue: Bool) -> Promise<Void> {

    guard _state.preferSubscribed != newValue else { return Promise(()) }

    guard let participant = participant else {
        log("Participant is nil", .warning)
        return Promise(EngineError.state(message: "Participant is nil"))
    }

    _state.mutate { $0.preferSubscribed = newValue }

    return participant.room.engine.signalClient.sendUpdateSubscription(
        participantSid: participant.sid,
        trackSid: sid,
        subscribed: newValue
    )
}

How to implement this in Objective-C

**Comment by hiroshihorie** [comment]
Thanks for the report, I think this commit fixes this: https://github.com/livekit/client-sdk-swift/commit/8e1043d197ce11b835d948a14807fd4b001a7c3e
Will be in v2.
