### ISSUE TITLE
share screen,app became purpse

### ISSUE THREAD

**Issue by monkeyttttt** [livekit/client-sdk-swift#279]
**Describe the bug**
share screen,app became purpse

**SDK Version**
SDK1.1.0

**iOS/macOS Version**
xcode 15.0.1      IOS 17.1.1

**Steps to Reproduce**
join room , then share screen

**Expected behavior**
show UI  normal
**Screenshots**

https://github.com/livekit/client-sdk-swift/assets/4243863/b975d28e-5bb2-4396-99b5-2755aa3f65c7

**Logs**
Please provide logs if you can.

**Comment by GiauHuynhWiki** [comment]
Hi @monkeyttttt , can I get in touch with you?
I have some question about screen sharing feature.

**Comment by monkeyttttt** [comment]
> Hi @monkeyttttt , can I get in touch with you? I have some question about screen sharing feature.

thanks,the problem have been resolved

**Comment by monkeyttttt** [comment]
remove   localParticipant.setScreenShare(enabled: true)  to

room.connect(wsURL, token).then { room in
room. localParticipant?.setScreenShare(enabled: true) 
}.catch { error in
// failed to connect
}

solved the problem
