### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by Aayush9029** [livekit/client-sdk-swift#288]
### Title: Request for watchOS Support in Swift SDK

**Is your feature request related to a problem? Please describe.**
Currently, the LiveKit Swift SDK does not offer support for watchOS. This limitation restricts the development of real-time audio applications on Apple Watch, which is increasingly becoming a popular platform for personal communication and health applications. I find it challenging to extend our application's reach to Apple Watch users due to this gap.

**Describe the solution you'd like**
I would like the LiveKit Swift SDK to include support for watchOS. This would enable developers to integrate real-time communication features directly into Apple Watch apps, expanding the scope of interaction and connectivity options available on the watchOS platform.

**Describe alternatives you've considered**
Indirect methods of communication between the Apple Watch and a paired iPhone to handle real-time interactions, but this is not as efficient or seamless as direct watchOS support would be. Another option could be using other SDKs that support watchOS, but this would lead to a fragmented codebase and potentially a less consistent user experience.

**Comment by hiroshihorie** [comment]
We weren't able to support watchOS directly due many missing components on the device such as Networking, Audio etc.
We support almost all platforms except watchOS.
