### ISSUE TITLE
if participant leave, delegate participantDidDisconnect participant.identity is null

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-swift#300]
**Describe the bug**
If someone leaves and triggers `participantDidConnect`, then we cannot get identity in RemoteParticipant

**SDK Version**
The latest version

**iOS/macOS Version**
ALL

**temporary solution**

Participant.swift

```
func cleanUp(notify _notify: Bool = true) async {
    await unpublishAll(notify: _notify)
    // Reset state
    _state.mutate { $0 = State(sid: $0.sid, identity: $0.identity, name: $0.name) }
    //_state.mutate { $0 = State(sid: "", identity: "", name: "") }
}
```

**Comment by hiroshihorie** [comment]
Thanks for the report will fix this

**Comment by wzJun1** [comment]
I think the problem arises again, after `participantDidDisconnect` is called, identity is null.

**Comment by patryk-sredzinski** [comment]
I can confirm this as well

**Comment by hiroshihorie** [comment]
This PR https://github.com/livekit/client-sdk-swift/pull/361 should fix it.

**Comment by kwanghyun-two** [comment]
I have same issue. When the fix will be available?

**Comment by patryk-sredzinski** [comment]
@hiroshihorie Can we get this one fixed?

**Comment by hiroshihorie** [comment]
Hello this is fixed in https://github.com/livekit/client-sdk-swift/pull/408
Will be in next release

**Comment by hiroshihorie** [comment]
This should be fixed now
