### ISSUE TITLE
If you switch the camera on and off multiple times, it will crash when exiting or disconnecting.

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-swift#313]
**Describe the bug**
If you switch the camera on and off multiple times, it will crash when exiting or disconnecting.

**SDK Version**
SDK: The latest version
Server: 1.5.2

git clone from `main`
```
git clone https://github.com/livekit/client-sdk-swift.git
```

**iOS/macOS Version**
16.2

**Steps to Reproduce**
Continuously switch the camera on and off, and it will crash after disconnecting or unpublishing after about 15-20 times.

**Screenshots**

![](https://s2.loli.net/2024/01/18/7IR3b9Qi6UNxjtw.png)

**Comment by hiroshihorie** [comment]
Thanks, will fix this !

**Comment by hiroshihorie** [comment]
I've updated the main branch, can you try it out.

**Comment by wzJun1** [comment]
Great, it's fixed
