### ISSUE TITLE
turn off shareScreen,but RPSystemBroadcastPickerView Cann't be closed

### ISSUE THREAD

**Issue by monkeyttttt** [livekit/client-sdk-swift#326]
when turn off shareScreen, the Broadcast is still exist
![WechatIMG42](https://github.com/livekit/client-sdk-swift/assets/4243863/41f81761-788a-4ff8-9fd7-919f4627ffc0)

IBAction func shareOrNot(_ sender: UIButton) {
        sender.isSelected = !sender.isSelected
        room.localParticipant?.setScreenShare(enabled: sender.isSelected)
        if(!sender.isSelected){
            let publications = localParticipant?.localVideoTracks.filter({$0.source == .screenShareVideo})
            if let localTrackPublication = publications?.first{
                localTrackPublication.mute().then{[weak self] in
                    self?.localParticipant?.unpublish(publication: localTrackPublication).then{
                    
                    }
                }
            }
        }
    }

_Originally posted by @monkeyttttt in https://github.com/livekit/client-sdk-swift/issues/223#issuecomment-1913856772_
        

@hiroshihorie @dsa

**Comment by GiauHuynhWiki** [comment]
Hi @monkeyttttt can I get in touch with you? I have some problems with screen sharing ios.

**Comment by monkeyttttt** [comment]
> Hi @monkeyttttt can I get in touch with you? I have some problems with screen sharing ios.

 What problem

**Comment by GiauHuynhWiki** [comment]
<img width="878" alt="Screenshot 2024-01-30 at 13 38 54" src="https://github.com/livekit/client-sdk-swift/assets/97865614/a090cc9d-82bd-4d31-8624-473eeb8e2f66">

My share screen track works only in-app, when I minimize to home, the screen share track (viewed from other device) will pause, and when I back to app again, the screen share track continues to work!!!

I think cause is I setup Broadcast Upload Extension wrong way.

**Comment by GiauHuynhWiki** [comment]
Is there any way to make sure I have it set up Broadcast Upload Extension correctly?
Seem it's can't debug, print... directly.

**Comment by monkeyttttt** [comment]
> <img alt="Screenshot 2024-01-30 at 13 38 54" width="878" src="https://private-user-images.githubusercontent.com/97865614/300703834-a090cc9d-82bd-4d31-8624-473eeb8e2f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTcyNDMsIm5iZiI6MTcwNjU5Njk0MywicGF0aCI6Ii85Nzg2NTYxNC8zMDA3MDM4MzQtYTA5MGNjOWQtODJiZC00ZDMxLTg2MjQtNDczZWViOGUyZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzM2Q3NDE3MDc5MGRlY2E1NGFlNzJhY2ZkMjUwZTgxNjdjZTRiZGQ2NThjZDBkZGJmMWM2NTI4YWI5MDcwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7n9mpinZm2jzrGWjqb0g-Ddg75Q9AXKCep7pD83Y51o">
> My share screen track works only in-app, when I minimize to home, the screen share track (viewed from other device) will pause, and when I back to app again, the screen share track continues to work!!!
> 
> I think cause is I setup Broadcast Upload Extension wrong way

you can get it,If config  useBroadcastExtension right in RoomOption

**Comment by GiauHuynhWiki** [comment]
@monkeyttttt Where I config useBroadcastExtension in RoomOption?

**Comment by GiauHuynhWiki** [comment]
<img width="514" alt="Screenshot 2024-01-30 at 14 36 53" src="https://github.com/livekit/client-sdk-swift/assets/97865614/2fa52f00-486a-4e62-b36c-f79fa991b7a2">
Hi @monkeyttttt , extremely grateful to you, after create RoomOptions then add it to room.connect.
It works perfectly now.
You made my day, bro.

**Comment by monkeyttttt** [comment]
replace sdk 1.0.13,the bug  have been resolved
