### ISSUE TITLE
Can't publish video track and preview in SwiftUIVideoView doesn't work 

### ISSUE THREAD

**Issue by creativecbr** [livekit/client-sdk-swift#330]
**Describe the Bug**

I am encountering an issue with screen share previews using the following code:

```swift
SwiftUIVideoView(track, layoutMode: .fit,
                 renderMode: .auto,
                 debugMode: false)
``` 

The video tracks are configured in the same manner as in the sample Swift app. I am publishing video tracks gathered by the following method:

```swift
let source = MacOSScreenCapturer.sources(for: .display, includeCurrentApplication: true)[0]!

let localVideoTrackForMainDisplay = LocalVideoTrack.createMacOSScreenShareTrack(source: source, options: SessionController.defaultScreenShareCaptureOptions)

guard let capturer = localVideoTrackForMainDisplay.capturer as? MacOSScreenCapturer,
      let mainWindowSource = capturer.captureSource else {
    
    logger.debug("Couldn't receive display source, error")
    completionHandler?(false)
    return
}

completionHandler?(true)
self.connect(using: configuration, with: mainWindowSource)
``` 

The publishing method returns an immediate error: "timed out," and previews do not return any frames from the screen. Notably, it worked correctly on the released version 1.1.6, and there have been no changes to the code for this preview and initialization.

On macOS 14.1, it works correctly from the main branch.

**SDK Version**

I pulled the SDK version directly from the **main** branch to incorporate changes from https://github.com/livekit/client-sdk-swift/issues/266, as it has not been released yet. Version 1.1.6 functions correctly.

**iOS/macOS Version**
macOS 12.7.1 

**Steps to Reproduce**

0. Download the sample macOS app.
1. Change LiveKit version to gather directly from the main branch.
2. Adjust the required code to fit into the new LiveKit version.
3. Launch the macOS sample and attempt to preview or publish the video track.

**Expected Behavior**
The preview should work, and publishing should also function correctly.

**Logs**
I logged information during the restart of tracks: 

```swift
let sources = try await MacOSScreenCapturer.sources(for: .display, includeCurrentApplication: true)
let options = ScreenShareCaptureOptions(dimensions: .h360_43, fps: 5)//, includeCurrentApplication: true)
let _newTracks = sources.map { LocalVideoTrack.createMacOSScreenShareTrack(source: $0, options: options) }

logger.info("Found \(_newTracks.count) display sources for remote access")
```

It appears that the tracks are available; the issue may be located further in the code.

**Comment by creativecbr** [comment]
The problem occurs also on just released 2.0.0.

**Comment by pblazej** [comment]
@creativecbr is it still reproducible in the latest (2.6.x) version?

```swift
try await room.localParticipant.setScreenShare(enabled: enable)
```

**Comment by pblazej** [comment]
I cannot reproduce this one on macOS 15.5, SDK v2.7.x.

It uses essentially the same code path as the example app:
https://github.com/livekit/client-sdk-swift/blob/83199f7656696bb9c6c6fc4bd5ff8eda10e2cb55/Sources/LiveKit/Participant/LocalParticipant.swift#L397-L405
