### ISSUE TITLE
Implicit use of "self" error in Xcodebuild 14.2

### ISSUE THREAD

**Issue by indaos** [livekit/client-sdk-swift#336]
**Describe the bug**
I get an error when I try to build a project with a LiveKit dependency.
---
Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/client-sdk-swift/Sources/LiveKit/Track/AudioManager.swift:228:69: error: implicit use of 'self' in closure; use 'self.' to make capture semantics explicit
                let configureFunc = newState.customConfigureFunc ?? defaultConfigureAudioSessionFunc
----
**SDK Version**
2.0.1

**iOS/macOS Version**
Xcodebuild 14.2

**Comment by hiroshihorie** [comment]
Hello can you try v2.0.2 ? Thanks for the report.
