### ISSUE TITLE
[Mac Catalyst] Incorrect video rotation

### ISSUE THREAD

**Issue by hiroshihorie** [livekit/client-sdk-swift#343]
**Describe the bug**
Video appears 90 degrees rotated incorrectly. 

I think some logic in WebRTC's RTCCameraCapturer that determines rotation works differently somehow for catalyst, so I need to make a patch in WebRTC. 

**SDK Version**
v2.0.4

**iOS/macOS Version**
Any supported version

**Steps to Reproduce**
Publish local track

**Expected behavior**
Correct rotation

Related: #340

**Comment by hiroshihorie** [comment]
Do you also see this with Mac Catalyst ?

**Comment by rdougan** [comment]
Yeah, I see the rotation issue on Mac Catalyst. You can fix the rotation by using rotation override. However on the client, you have to then detect the rotation issue and fix it in there as well. In my case, the client is JS and I’m using css to transform the video element.

**Comment by hiroshihorie** [comment]
I think this will fix it:
https://github.com/webrtc-sdk/webrtc/pull/126

**Comment by hiroshihorie** [comment]
Merged in main and will be in next release
