### ISSUE TITLE
Error build project with 2.0.4 version with LiveKit on Xcode 15.2

### ISSUE THREAD

**Issue by Viktorianec** [livekit/client-sdk-swift#345]
**Describe the bug**
Xcode 15.2 compiling error as SPM dependency.
Duplicate interface definition for class 'Sid' etc.

**SDK Version**
2\\\\\\\\.0.4

**Screenshots**

![Example — LiveKit-Swift h 2024-02-22 12-43-04](https://uploads.linear.app/65f9603c-a265-4a1f-8af0-4c2243b87ade/3765a1a2-d4cf-4ab1-8558-58f17594de59/ee181565-ee05-407d-8841-91ae0bdf5764?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1Zjk2MDNjLWEyNjUtNGExZi04YWYwLTRjMjI0M2I4N2FkZS8zNzY1YTFhMi1kNGNmLTRhYjEtODU1OC01OGYxNzU5NGRlNTkvZWUxODE1NjUtZWUwNS00MDdkLTg4NDEtOTFhZTBiZGY1NzY0IiwiaWF0IjoxNzA4NjAzNzMxLCJleHAiOjMzMjc5MTYzNzMxfQ.FbO3uccBznFtgbCW-HwNdI4Fp_6vn-rEJZZ8DaWRfHY)

**Comment by hiroshihorie** [comment]
I think there's an issue with nested symbols, can you try this branch ?
https://github.com/livekit/client-sdk-swift/tree/rename-objc-nested-symbols

**Comment by Viktorianec** [comment]
@hiroshihorie Thank you, solution from https://github.com/livekit/client-sdk-swift/tree/rename-objc-nested-symbols worked. I linked it to needed targets and now everything's fine.

**Comment by hiroshihorie** [comment]
This is in v2.0.5

**Comment by Viktorianec** [comment]
I'm getting another error:
Missing required module 'CHeaders'
![2024-03-11 10 17 42](https://github.com/livekit/client-sdk-swift/assets/3342027/21ee2cee-80b6-429b-a28a-af473c5505f2)

**Comment by hiroshihorie** [comment]
I can't reproduce that, can you try resetting package cache ?

**Comment by Viktorianec** [comment]
You were right, after resetting the cache everything is fine. Thank you for your hard work
