### ISSUE TITLE
Incompatibility Issue with @objc and non-protocol inheritance when BUILD_LIBRARY_FOR_DISTRIBUTION=YES

### ISSUE THREAD

**Issue by indaos** [livekit/client-sdk-swift#364]
Continuing the issue of using version 2 along with the BUILD_LIBRARY_FOR_DISTRIBUTION=YES option, 
it was somewhat helpful to remove CHeaders from the dependencies. 

However, a new problem has arisen related to the protocol declaration:

`@objc public protocol AudioTrack where Self: Track {}
`

When the BUILD_LIBRARY_FOR_DISTRIBUTION option is used, the LiveKit.swiftinterface file has the following code:

`@objc public protocol LocalTrack : LiveKit.Track {}
`

Here, the use of @objc is incompatible with inheriting from the non-protocol type "Track" 

Can you help resolve this issue, please?

**Comment by hiroshihorie** [comment]
Hello, which Xcode version are you using ?
