### ISSUE TITLE
Quality issue in mobile data

### ISSUE THREAD

**Issue by aravind0304** [livekit/client-sdk-swift#374]
**Describe the bug**
when we are using mobile data it is showing very low quality
**SDK Version**
latest version
**iOS/macOS Version**
latest version
**Steps to Reproduce**
use mobile data and connect 

**Expected behavior**
a good quality required
**Screenshots**
na
**Logs**
na

**Comment by aravind0304** [comment]
I am waiting for response from team

**Comment by hiroshihorie** [comment]
Hello, I need a bit more information from your side. Please make sure your network is good.

**Comment by hiroshihorie** [comment]
Hello, I will close this for now. I think it's your network issue.
