### ISSUE TITLE
Participant unable to join room with a token which contains "canSubscribe": false in IOS SDK 2.0.7

### ISSUE THREAD

**Issue by royatanu94** [livekit/client-sdk-swift#380]
**Describe the bug**
Hi All,
Found an issue with ios sdk, where if you try to join with a token which contains "canSubscribe": false, it gives error Invalid state(Publisher is nil)
but same works in other sdk.
**SDK Version**

Please provide the SDK version.
2.0.7
**iOS/macOS Version**
IOS
The OS version which the issue occurs.
ios17
**Steps to Reproduce**
Try to join room with "canSubscribe": false permission, it will fail.

Token created using:
{
    "identity": "atanu-ios1",
    "room": "demo-room-ios-test",
    "roomJoin": true,
    "canPublish": true,
    "canPublishData": false,
    "canSubscribe": false,
    "roomCreate" : false,
    "roomAdmin" : false,
    "roomList": true,
    "roomRecord": false,       
    "metadata": "data1",
    "canPublishSources": [
        "MICROPHONE",
        "CAMERA",
        "SCREEN_SHARE"
    ]
}

**Expected behavior**
User should able to join room where user will only publish data won't subscribe other tracks using "canSubscribe": false attribute in token.

**Screenshots**
<img width="323" alt="image" src="https://github.com/livekit/client-sdk-swift/assets/30543092/0b6ba91e-5d30-4099-92b2-e21d4a8b4a81">

**Logs**
Room.cleanUp(withError:isFullReconnect:) withError: Optional(Error Domain=.xxx Code=104 "Invalid state(Publisher is nil)" UserInfo={NSLocalizedDescription=Invalid state(Publisher is nil)})

**Comment by hiroshihorie** [comment]
Thanks for reporting.
This [has been fixed](https://github.com/livekit/client-sdk-swift/commit/41b2f9ea8fc3068d531145c2e7cbac0cba4b93bc) and [confirmed with updated tests ](https://github.com/livekit/client-sdk-swift/pull/397). This will be in the next version.
I will close this for now.
