### ISSUE TITLE
After pulling the source code locally, some Delegates will report errors

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-swift#414]
**Describe the bug**
After pulling the source code locally, some Delegates will report errors

**SDK Version**
2.0.10 ~ 2.0.11

**iOS/macOS Version**
iOS17.2

**Steps to Reproduce**

No need for Swift Package Manager, simply pull the source code locally

1. Connect Room
2. Open Camera
3. Crash

If I remove `@objc`, it will work normally. (or do I just use `newValue?.delegates.add(delegate: self) ` It also works (but the entire livekit sdk has too many delegates, it is too troublesome to change them all)

I feel like it's a problem with the Swift version being too high, but I don't know how to solve it.

**Screenshots**
![171719461830_ pic](https://github.com/livekit/client-sdk-swift/assets/52230047/0391bb9b-2070-40dd-ab8c-1280b38ab436)
<img width="1040" alt="iShot_2024-06-27_12 17 30" src="https://github.com/livekit/client-sdk-swift/assets/52230047/a5446866-0504-4854-b88d-562673686f4e">

**Comment by hiroshihorie** [comment]
Can you tell me what's your Xcode version ?

**Comment by wzJun1** [comment]
1. Xcode 15.4 and Swift 5.10
2. Swift
3. Yes

**Comment by wzJun1** [comment]
My current solution is to no longer use `add` and `remove` with `@objc`, but instead use `xxx.delegates.add()` directly.

eg: 

<img width="643" alt="iShot_2024-06-27_14 55 59" src="https://github.com/livekit/client-sdk-swift/assets/52230047/6b663ec4-e923-48f5-9ee9-91e1b583c76a">
<img width="836" alt="iShot_2024-06-27_14 56 07" src="https://github.com/livekit/client-sdk-swift/assets/52230047/f74c02cb-753c-4ad3-abf5-350736440c26">

**Comment by hiroshihorie** [comment]
Hmm.. It's odd that you need to do that, is it only with TrackDelegate ?

**Comment by wzJun1** [comment]
Not only 'TrackDelegate', but all `delegate` `add` `remove` with `@objc`, as shown in the screenshot below, are like this.

<img width="868" alt="iShot_2024-06-27_17 50 57" src="https://github.com/livekit/client-sdk-swift/assets/52230047/19c2e5fc-5fd8-474f-adde-f9554fe6fe20">
<img width="441" alt="iShot_2024-06-27_17 52 21" src="https://github.com/livekit/client-sdk-swift/assets/52230047/fbf6c75b-954e-419f-bc63-b05be17b0d99">

**Comment by hiroshihorie** [comment]
Hmm looks like some Xcode bug, I'm not sure how to reproduce this at the moment.

**Comment by wzJun1** [comment]
Okay, then I will continue to follow up
