### ISSUE TITLE
Unable to switch to speaker output when bluetooth headsets are connected

### ISSUE THREAD

**Issue by TypiYerke** [livekit/client-sdk-swift#415]
**Describe the bug**
Unable to switch to speaker output when bluetooth headsets are connected
Is there way to change output audio to BluetoothHeadset, Earpiece, Speakerphone in real time ? I used AudioManager.shared.preferSpeakerOutput = true/false to dynamic/speaker, but its not working when  bluetooth headsets are connected

**SDK Version**
LiveKit 1.1.6

**iOS/macOS Version**
iOS 17.4.1

**Xcode Version**
15.2
(Please provide the Swift version if you know it)

**Steps to Reproduce**
I used AudioManager.shared.preferSpeakerOutput = true/false to dynamic/speaker, but its not working when  bluetooth headsets are connected

**Comment by davidzhao** [comment]
Please update to the latest version of the SDK, 1.1.6 is quite old and is unsupported at this point.

You can also try [customizing the audio session](https://github.com/livekit/client-sdk-swift?tab=readme-ov-file#audiosession-management) and set [defaultToSpeaker](https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616462-defaulttospeaker) to true
