### ISSUE TITLE
Screenshare audio for IOS sdk

### ISSUE THREAD

**Issue by royatanu94** [livekit/client-sdk-swift#417]
**Is your feature request related to a problem? Please describe.**
Currently IOS app does not support the audio of shared screen.

**Describe the solution you'd like**
IOS app should support screenshare audio like web sdk has.

**Describe alternatives you've considered**

**Additional context**

**Comment by hiroshihorie** [comment]
Hi, unfortunately this is not supported at the moment .
I would definitely like to implement this.

**Comment by hiroshihorie** [comment]
This is related / duplicate of https://github.com/livekit/client-sdk-swift/issues/385
I will close this one.
