### ISSUE TITLE
CocoaPods outdated

### ISSUE THREAD

**Issue by patryk-sredzinski** [livekit/client-sdk-swift#419]
Currently if we import LiveKitClient via Cocoapods, we receive 2.0.9.

I reported it previously when we were on 2.0.9 and CocoaPods was 2.0.5 - #387 
Now we have the same, I believe it must be pushed to CocoaPods specs

**Comment by patryk-sredzinski** [comment]
Hey, any progress on this please?
I am having the issue that was fixed in newest version with participantDidDisconnect delegate

**Comment by hiroshihorie** [comment]
v2.0.11 has been published please try.
