### ISSUE TITLE
CocoaPods version requires experimental feature: AccessLevelOnImport

### ISSUE THREAD

**Issue by patryk-sredzinski** [livekit/client-sdk-swift#425]
When using LiveKitClient via CocoaPods, you'll encounter this error.

![Screenshot 2024-07-08 at 16 41 59](https://github.com/livekit/client-sdk-swift/assets/23390884/1ab07836-6551-4d33-8d74-c6ec9eddfcde)

I believe podspec file requires some changes to enable this feature

**Comment by YingW1012** [comment]
我也遇到了、什么时候能修复呀

**Comment by hiroshihorie** [comment]
Please try version `2.0.12` and re-open if not resolved yet.

**Comment by YingW1012** [comment]
还是没有解决哦

**Comment by YingW1012** [comment]
/Users/wangdada/project/ios-project/WYCallKit/Pods/LiveKitClient/Sources/LiveKit/Types/Options/AudioCaptureOptions.swift:20:1: error: Access level on imports require '-enable-experimental-feature AccessLevelOnImport'
internal import LiveKitWebRTC
^~~~~~~~~
/Users/wangdada/project/ios-project/WYCallKit/Pods/LiveKitClient/Sources/LiveKit/Types/Options/AudioCaptureOptions.swift:20:17: error: ambiguous implicit access level for import of 'LiveKitWebRTC'; it is imported as 'internal' elsewhere
internal import LiveKitWebRTC
                ^
         internal

**Comment by std-s** [comment]
Hi, the problem still exists in 2.0.14.

**Comment by hiroshihorie** [comment]
Should be fixed in new release 2.0.14
