### ISSUE TITLE
Audio Session Custom Configuration

### ISSUE THREAD

**Issue by spacex81** [livekit/client-sdk-swift#445]
**Describe the bug**
When I replace the LiveKit default audio session configuration code to custom configuration code, not able to publish local track. and get this error

// ERROR
AURemoteIO.cpp:1702  AUIOClient_StartIO failed (561145187)
//
**SDK Version**
Please provide the SDK version.
2.0.12

**iOS/macOS Version**
The OS version which the issue occurs.
Minimum deployment 17.5

**Xcode Version**
The Xcode version which the issue occurs.
(Please provide the Swift version if you know it)
XCode Version 15.4 (15F31d)
Swift    Version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)

**Steps to Reproduce**
1. set 'customConfigureAudioSession' function in 'init()'
2. connect to LiveKit room
3. run 'publishAudio' function

**Expected behavior**
'customConfigureAudioSession' function is exactly same with 'defaultConfigureAudioSessionFunc'.
(just replace 'LKRTCAudioSessionConfiguration' with 'RTCAudioSessionConfiguration', 
and replace 'LKRTCAudioSession' with 'RTCAudioSession')

so I expect the behavior to be the same with default livekit

**Logs**
AURemoteIO.cpp:1702  AUIOClient_StartIO failed (561145187)
[sample.swift.zip](https://github.com/user-attachments/files/16406262/sample.swift.zip)

**Comment by hiroshihorie** [comment]
You're probably not setting the correct audio session category.

**Comment by spacex81** [comment]
yeah you are right.
fixing audio session configuration code handled the issue.

Thank you for reply

2024년 7월 29일 (월) 오후 8:41, Hiroshi Horie ***@***.***>님이 작성:
