### ISSUE TITLE
Stop Broadcast Extension by pressing indicator on native time doesn't make isScreenShareEnabled() to return false

### ISSUE THREAD

**Issue by mokuzuu** [livekit/client-sdk-swift#446]
**Describe the bug**
Even after stopping screen share by pressing indicator on native time doesn't make isScreenShareEnabled() to return false.

**SDK Version**
2.0.12

**iOS/macOS Version**
iOS 17.5.1

**Xcode Version**
15.4
Swift 5

**Steps to Reproduce**
1. Start broadcast extension by calling setScreenShare(enabled: true)
2. Stop screen share by pressing indicator on native time

**Expected behavior**
Expect `room.localParticipant.isScreenShareEnabled()` to return `false` but `true` is returned. 

**Screenshots**

**Logs**
Please provide logs if you can.

**Comment by mokuzuu** [comment]
I think I could workaround this by listening to `iOS_BroadcastStopped` notification from CFNotificationCenter

(DarwinNotificationCenter is extended by following https://gist.github.com/tomlokhorst/7fe49a03b8bac960eeaf2b991faa3680 so that handler can use async)
```
 func notificationCallback() {
        DispatchQueue.global().async {
            Task {
                await performAsyncTask()
            }
        }
    }

DarwinNotificationCenter.shared.addObserver(name: "iOS_BroadcastStopped", callback: notificationCallback)
```

**Comment by mokuzuu** [comment]
Probably I can address fix for #444 with similar approach

**Comment by ashwin-nath-m** [comment]
@mokuzuu did u get this working? can u share your DarwinNotificationCenter class

**Comment by mokuzuu** [comment]
I could workaround like this

```
 @State var darwinNotificationCenterObservation: DarwinNotificationObservation?

 // Define an async function to perform the async task
    func performAsyncTask() async {
        do {
            try await room.localParticipant.setScreenShare(enabled: false)
        } catch {
            print("An error occurred while updating screen share")
        }
    }
    
    // function that matches the C function pointer type
    func notificationCallback() {
        // Dispatch to handle async code
        DispatchQueue.global().async {
            Task {
                await performAsyncTask()
            }
        }
    }
    
    
    func setupNotifications() {
        // We need to store the value in variable/state to keep notification active.
        darwinNotificationCenterObservation = DarwinNotificationCenter.shared.addObserver(name: "iOS_BroadcastStopped", callback: notificationCallback)
    }
```
