### ISSUE TITLE
Allow clients to turn on AudioCaptureOptions's experimentalNoiseSuppression flag.

### ISSUE THREAD

**Issue by dfed** [livekit/client-sdk-swift#454]
**Is your feature request related to a problem? Please describe.**
Our team would like to experiment with [`googNoiseSuppression2`](https://github.com/livekit/client-sdk-swift/blob/2de7288b006cc0270048ba50b5436fbc6d44127b/Sources/LiveKit/Track/Local/LocalAudioTrack.swift#L51), which requires enabling the [`experimentalNoiseSuppression`](https://github.com/livekit/client-sdk-swift/blob/2de7288b006cc0270048ba50b5436fbc6d44127b/Sources/LiveKit/Types/Options/AudioCaptureOptions.swift#L43C16-L43C44) flag. However, this flag is a `let` constant, set to `false`, and is not settable in [the initializer](https://github.com/livekit/client-sdk-swift/blob/2de7288b006cc0270048ba50b5436fbc6d44127b/Sources/LiveKit/Types/Options/AudioCaptureOptions.swift#L48-L53) for the `AudioCaptureOptions` type.

**Describe the solution you'd like**
Make `experimentalNoiseSuppression` settable in the `AudioCaptureOptions` initializer.

**Describe alternatives you've considered**
Make `experimentalNoiseSuppression` a `var`, but that doesn't seem like a correct approach given that these options are all constants.

**Additional context**
I'd be happy to put up a PR that does this, though I'm curious to learn if there's a strong reason *not* to use this API today.

**Comment by hiroshihorie** [comment]
I haven't been able to find evidence that this is used in WebRTC, was planning to remove these.
Please let me know if I'm wrong.

**Comment by dfed** [comment]
Ah, [shoot](https://chromium.googlesource.com/external/webrtc/+/93348d89bc3cc77394b77915b5b2c0a033f401df) – you are correct!
