### ISSUE TITLE
Change buffer size of sent audio track

### ISSUE THREAD

**Issue by ondrejkorol** [livekit/client-sdk-swift#484]
Hi @hiroshihorie,

I’m looking for some guidance on managing the audio buffer size when sending data via the LiveKit Swift SDK. Currently, the SDK sends audio data in 10ms chunks, but I need to adjust it to send larger chunks (e.g., 30-60ms).

**Is your feature request related to a problem? Please describe.**
Yes, the receiver expects larger audio chunks (30-60ms), and the current 10ms chunks aren’t compatible with this requirement.

**Describe the solution you’d like**
I’d like to have the ability to adjust the buffer size of the sent/received PCM audio buffer, similar to how the Python SDK provides source.capture_frame.

Is there any way to configure this buffer size in the Swift SDK, or would it require a feature update?

Thanks in advance for your help!

Ondrej

**Comment by ondrejkorol** [comment]
I got the response from the LiveKit team:
> This is fixed in WebRTC and cannot be changed in the Swift SDK.

Closing the issue:)

**Comment by Abilashs003** [comment]
Can we do adjust the Buffer size of PCM streamed from livekit let me know? I am using livekit nodejs sdk
