### ISSUE TITLE
OpenAI speech to speech, is it available? 

### ISSUE THREAD

**Issue by ruofeilyu** [livekit/client-sdk-swift#496]
<img width="784" alt="Screenshot 2024-10-01 at 4 39 09 PM" src="https://github.com/user-attachments/assets/3170920d-cbe3-45db-b6e2-8d2a72f24732">

https://livekit.io

But I can't see the swift one for this speech to speech feature.

**Comment by bcherry** [comment]
response in community slack! (tl;dr; yes via our agents framework)

 https://livekit-users.slack.com/archives/C07FVFGAUKX/p1727827665980609?thread_ts=1727826992.492279&cid=C07FVFGAUKX
