### ISSUE TITLE
Custom Video Source using AVFoundation

### ISSUE THREAD

**Issue by andreasteich** [livekit/client-sdk-swift#501]
I'm looking for a way to add a custom video source like providing the video frames by AVCapturesession with a custom captureOutput implementation. Is that possible using LiveKit?

**Comment by ming-chu** [comment]
I want to implement the custom CameraCapturer too.

But looks like it was using `RTCCameraVideoCapturer` from webrtc and also cannot extends `VideoCapturer` outside the module.

**Comment by andreasteich** [comment]
From my point of view, it would be enough to know how to feed the frames to webrtc manually. So I could retrieve the frames via `captureOutput` and hand them over to WebRTC `videoCapturer`?

**Comment by ming-chu** [comment]
@andreasteich then I think maybe you want something like this `LocalVideoTrack.createBufferTrack()`.

**Comment by andreasteich** [comment]
Okay thank you very much! Do you have some more informarion about that? Can't find documentation for that...

**Comment by andreasteich** [comment]
You're amazing thank you very much!

**Comment by ming-chu** [comment]
> You're amazing thank you very much!
> 
> So if I understand it correctly, when I'm receiving `CMSampleBuffers` inside `captureOutput` of `AVCaptureSession`, I can pass those buffers on to the `capturer.capture(...)` with proper configuration provided for `BufferCapturer` and `LocalVideoTrack` on setup? 
> 
> Can you confirm @ming-chu ?

I think so, but honestly I didn't tested it out. I would like to hear from you about the results 😃

**Comment by andreasteich** [comment]
So I keep this issue until implementation done. Thank you very much!

**Comment by andreasteich** [comment]
@Negi-Rohit yes, was able to do so by following @ming-chu instructions. Just Create the `BufferTrack` and pass it some `CMSampleBuffer` or `CVPixelBuffer` objects. 

Works incredibly well!

**Comment by PiyushSaneparaTPC** [comment]
Thanks @ming-chu with this I can send my buffer
