### ISSUE TITLE
Accessing the camera while multitasking on background doesn't work

### ISSUE THREAD

**Issue by mokuzuu** [livekit/client-sdk-swift#504]
**Describe the bug**
I followed Apple doc to enable background camera access ([doc](https://developer.apple.com/documentation/avkit/accessing-the-camera-while-multitasking-on-ipad)) but it still doesn't give the app to access camera on background.

**SDK Version**
Please provide the SDK version.

2.0.16

**iOS/macOS Version**
The OS version which the issue occurs.
iOS 18

**Xcode Version**
The Xcode version which the issue occurs.
(Please provide the Swift version if you know it)

XCode: 16.0
Swift version (result of running `xcrun swift -version`):  `swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx14.0`

**Steps to Reproduce**
1. Clone minimal-pip example
2. Update LiveKit library
3. Make changes to `minimal-pip/minimal-pip/RoomView.swift`
```
struct RoomView: View {
...

var body: some View {
        ...
        .onAppear(perform: {
            try await room.connect(...)

           // NEW CODE
            try await room.localParticipant.setCamera(enabled: true)
            if let localVideoTrack = room.localParticipant.trackPublications.first(where: {
                        $0.value.kind == Track.Kind.video
                    })?.value.track as? LocalVideoTrack  {
             
                        if let cameraCapturer = localVideoTrack.capturer as? CameraCapturer, cameraCapturer.isMultitaskingAccessSupported {
                 
                            // Configure the capture session.
                            cameraCapturer.captureSession.beginConfiguration()
                            cameraCapturer.isMultitaskingAccessEnabled = true
                            
                            defer {
                                cameraCapturer.captureSession.commitConfiguration()
                                cameraCapturer.captureSession.startRunning()
                            }
                        }
                    }
           // NEW CODE ENDS
        }
    }
}
```
4. Run the app, and join same room as another livekit participant. 
5. Go to background on this app. PiP should work but background camera access doesn't

**Expected behavior**
An App should have access to camera on background.

**Screenshots**

**Logs**
Please provide logs if you can.

**Comment by hiroshihorie** [comment]
Thanks for the report, I might need to patch WebRTC.
I think it always suspends the capture session in background.

**Comment by hiroshihorie** [comment]
@davidliu Good point, updating the example now,
also RoomOptions.suspendLocalVideoTracksInBackground needs to be false.

**Comment by hiroshihorie** [comment]
@mokuzuu Doing this works:
```swift
localVideoTrack = LocalVideoTrack.createCameraTrack()
Task {
    if let cameraCapturer = localVideoTrack?.capturer as? CameraCapturer {
        cameraCapturer.isMultitaskingAccessEnabled = true
    }
    try await localVideoTrack?.start()
}
```

**Comment by mokuzuu** [comment]
@hiroshihorie @davidliu 
Thank you so much guys. You guys are absolute legends 🚀

**Comment by mokuzuu** [comment]
For people who face this issue, you would want to set `isMultitaskingAccessEnabled = true` to camera capturer from `room.localParticipant.trackPublications` as I faced the issue `room.localParticipant.firstCameraVideoTrack.capturer.switchCameraPosition` stops working. My final code looks like this

```
 let room = try await roomCtx.connect(opts: opts)


                        if let localVideoTrack = room.localParticipant.trackPublications.first(where: {
                            $0.value.kind == Track.Kind.video
                        })?.value.track as? LocalVideoTrack  {
                            
                            if let cameraCapturer = localVideoTrack.capturer as? CameraCapturer, cameraCapturer.isMultitaskingAccessSupported {
                                
                                // Configure the capture session.
                                cameraCapturer.captureSession.beginConfiguration()
                                cameraCapturer.isMultitaskingAccessEnabled = true
                                
                                
                                cameraCapturer.captureSession.commitConfiguration()
                                cameraCapturer.captureSession.startRunning()
                                Task {
                                    try await localVideoTrack.start()
                                }
                                
                            }
                     }
```

Make sure you set `suspendLocalVideoTracksInBackground: false` to `room.connect(roomOptions: RoomOptions)`
