### ISSUE TITLE
Cannot revecive video track from iOS

### ISSUE THREAD

**Issue by sinhngn** [livekit/client-sdk-swift#61]
The delegate in below:
```func room(_ room: Room, participant: RemoteParticipant, didSubscribe publication: RemoteTrackPublication, track: Track)```
does not actived. Please help me how to make this function is called.
Thank you!

**Comment by sinhngn** [comment]
Oh thank you, but I have just known why!, At ConnectOptions in room.connect, I set publishOnlyMode = nil, everything work well! Maybe this options just use for broadcasting video!.
My mistake! Thank you for support!

**Comment by hiroshihorie** [comment]
Yes in most cases you won't need to use `publishOnlyMode`, 
if you use this mode `autoSubscribe` will be turned off so you will not receive track subscribe notifications.
