### ISSUE TITLE
hi, how can I join swift sdks into Object-c？ 

### ISSUE THREAD

**Issue by lixiaozhong** [livekit/client-sdk-swift#62]
hi, my friends, how can I join swift sdks into Object-c？ 
Can you help me？ I have no idea。Thank you very much！

**Comment by lixiaozhong** [comment]
Hi, actually, I’m not able to separate UI from the swift sdk code.

**Comment by davidzhao** [comment]
I believe you should be able to use Swift libraries from ObjC. What errors are you seeing?
