### ISSUE TITLE
Does VideoView work in iOS Simulator?

### ISSUE THREAD

**Issue by iAmcR** [livekit/client-sdk-swift#77]
Hi, 

I tried out the example (found here: https://github.com/livekit/client-example-collection-swift) on the iOS 15.4 simulator (Xcode 13.3.1). 

I noticed that when using a real device the collection view cell renders with video, but on the simulator no video is shown. 

Is that correct operation or is something not right?

Thank you.

**Comment by hiroshihorie** [comment]
Rendering on simulators don't work for now.

**Comment by iAmcR** [comment]
No worries. Thank you. 

It seems (this particular build of) `RTCMTLVideoView` doesn't render video on iOS simulator. But irrespective of performance, I really needed to quickly see a render on the simulator. I was able to add simulator rendering by adding: 

```
#if targetEnvironment(simulator)
        // iOS Simulator ---------------
        logger.log("Using RTCEAGLVideoView for VideoView's Renderer", type: VideoView.self)
        let eaglView = RTCEAGLVideoView()
        eaglView.contentMode = .scaleAspectFit
        result = eaglView
#else 
```

to the `createNativeRendererView()` function in the `VideoView` class.

**Comment by davidzhao** [comment]
thanks for the tip @iAmcR sounds like we should include this capability into the SDK. Would you be interested in submitting a PR?

**Comment by iAmcR** [comment]
@davidzhao You're welcome. Sure - I'd be interested in submitting a PR.

**Comment by iAmcR** [comment]
@davidzhao I submitted the PR as requested.

**Comment by davidzhao** [comment]
thank you @iAmcR !
