### ISSUE TITLE
How to custom camera/audio publish ?

### ISSUE THREAD

**Issue by sandeep-yudiz** [livekit/client-sdk-swift#92]
Hi

We have checked your documents but not much clear for custom camera/audio publish support?
Because our app we have beauty filter we need to apply on while publish video for streamer. 

Thank you

**Comment by hiroshihorie** [comment]
Which of the following are you trying to accomplish:
- Apply custom image processing to the frames captured by camera.
- You already have frames (CVPixelBuffer) being generated and you want to publish it.

**Comment by hiroshihorie** [comment]
Currently only capturing `CMSampleBuffer` is supported but I think it's not hard to convert a `CVPixelBuffer` into a `CMSampleBuffer`.

You can:
1. create a `BufferCapturer` by calling `LocalVideoTrack.createBufferTrack()`.
2. start generating frames and call `bufferTrack.capturer.capture(sampleBuffer)`
3. publish the track.
```swift
  self.bufferTrack = LocalVideoTrack.createBufferTrack()
  return room.localParticipant!.publishVideoTrack(track: self.bufferTrack!)
```

Here is a full example:
https://github.com/livekit/client-example-swift/blob/main/iOS/BroadcastExt/SampleHandler.swift

**Comment by hiroshihorie** [comment]
Hello with this commit:
https://github.com/livekit/client-sdk-swift/commit/27fa59136c57337343e94c91f15b785a86abd986

now you can directly capture a `CVPixelBuffer`.
