### ISSUE TITLE
Can streamer while streaming join other streamer for some battle feature requirements in our app?

### ISSUE THREAD

**Issue by sandeep-yudiz** [livekit/client-sdk-swift#93]
Hi

Can you please guide this feature support exists or not?

Thanks

**Comment by hiroshihorie** [comment]
Hi, are you talking about joining multiple rooms ? 👉 Yes you can.
Can you explain a bit more of your use case ?

**Comment by davidzhao** [comment]
As Hiroshi mentioned, LiveKit supports multiple rooms, and you are able to preview the next room while streaming a current one. I'm not sure what you mean by `in battle`, but it sounds like the rest are features specific to your application.

In either case, LiveKit should work for your use case and I'm closing the issue.
