### ISSUE TITLE
Monitor conference states by one user from several devices

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/client-sdk-swift#94]
I will describe the task.
Let's say there is a chat, the user has it on several devices at once and he can use them at the same time. It is necessary to make it so that the user, talking on the ios client, can connect to the conference from the web and automatically leave conference on ios. From same account on all devices user can see statuses of participants: joined/muted/active lists, but only from one device at same time he can be joined to conference.

Currently, the live kit does not provide such an opportunity.

One solution I see is a creating  additional service layer to that users can connect and listen information about conference (who is joined, active/inactive state).

And my question )
What is better solution? 
- create own stand alone service that will collect conference states from Livekit server via [webhooks](https://docs.livekit.io/guides/webhooks/) and publish to connected users
- My be cool thing to create some addon/extension for livekit, of course if its possible 

I will happy to any advise from you!

**Comment by davidzhao** [comment]
What you are describing is exactly the connection model that livekit uses. If you are passing in a consistent `identity` for the user across devices. Only one client could remain connected. See [connection docs](https://docs.livekit.io/guides/room/connect/#connecting-to-a-room).

**Comment by davidzhao** [comment]
in order to look at who's in the room *before* connecting to the room, you can either use the server APIs for this information. webhooks is a reasonable approach too.

**Comment by shalom-aviv** [comment]
Thanks!
