### ISSUE TITLE
Scalable codecs

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/client-sdk-swift#95]
Great topics I very recommend to read them all who want to use Livekit:
- [An Introduction to WebRTC Simulcast]( https://blog.livekit.io/an-introduction-to-webrtc-simulcast-6c5f1f6402eb/)
- [Bringing Zoom's end-to-end optimizations to WebRTC](https://stackoverflow.com/questions/37128928/does-webrtc-support-adaptive-bitrate-streaming-for-video)

We have 3 platforms ios/android/web(chrome, firefox). 
Is it reasonable to use some scalable codec now? 
If yes Which you advise?

**Comment by davidzhao** [comment]
While AV1 is supported by Chrome, SVC publishing has not been enabled by default yet. We are adding support for this into LiveKit for when browsers start to support it.
