### ISSUE TITLE
How to use SDK in 'cocoapods'.

### ISSUE THREAD

**Issue by std-s** [livekit/client-sdk-swift#98]
hi,
  how to use SDK in 'cocoapods'.

**Comment by davidzhao** [comment]
we have not yet published the SDK to cocoapods. You should be able to use Swift packages in addition to Cocoapods.

**Comment by tgyhlsb** [comment]
@davidzhao any plans to support Cocoapods? We are also building a library for both pods and SPM but can't embed `LiveKit` in the pod version.

**Comment by baveku** [comment]
> @davidzhao any plans to support Cocoapods? We are also building a library for both pods and SPM but can't embed `LiveKit` in the pod version.

@tgyhlsb  I rewrite this library to support Cocoapods, you can review it here: https://github.com/baveku/LiveKit
My lib is out of date. Next month, I will refactor and rewrite new version to support iOS and Cocoapods. Based on this library

**Comment by hiroshihorie** [comment]
Update: Cocoapods support should be available from next version. 🙂

**Comment by tgyhlsb** [comment]
I've seen this commit https://github.com/livekit/client-sdk-swift/commit/d7a68b34af8ab2c5e6312458f75f0795ae9bd862 \o/

Maybe it's too early, but it does not seem to have been pushed to trunk, right?

Thanks for working on it (:

**Comment by kubamatula** [comment]
I think that because `spec.source_files` is commented out in https://github.com/livekit/client-sdk-swift/blob/main/LiveKit.podspec - the Pod does not actually contain any LiveKit source files - and does not produce the framework correctly.

**Comment by hiroshihorie** [comment]
Hi, the podspec is published to Cocoapods with name `LiveKitClient`.

This is a minimal example including LiveKit with Cocoapods:
https://github.com/livekit/client-example-collection-swift/tree/main/using-cocoapods

I will close this for now.

**Comment by jlopesoares** [comment]
Hi, 
I've checked the `LiveKitClient` pod but I'm having some troubles when I try to archive a project while using it. It's related to a missing module.
Can you take a look? 


Thanks
